M48
; DRILL file {KiCad (6.0.0)} date Fri Jan 14 12:25:08 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-14T12:25:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X5.0Y-9.0
X5.0Y-28.0
X87.0Y-9.0
X87.0Y-28.0
T2
X5.0Y-4.5
X5.0Y-32.5
X87.0Y-4.5
X87.0Y-32.5
T0
M30
